kind: Deployment
apiVersion: apps/v1
metadata:
  name: hub-registration-controller
  labels:
    app: hub-registration-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-registration-controller
  template:
    metadata:
      labels:
        app: hub-registration-controller
    spec:
      serviceAccountName: default
      containers:
      - name: hub-controller
        image: quay.io/open-cluster-management/registration:latest
        imagePullPolicy: IfNotPresent
        args:
          - "/registration"
          - "controller"
          - "--kubeconfig=/var/run/secrets/hypershift/kubeconfig"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /var/run/secrets/hypershift
          name: kubeconfig
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: service-network-admin-kubeconfig 
